export type Category =
  | "Frucht"
  | "Beeren"
  | "Menthol"
  | "Dessert"
  | "Getraenke"
  | "Tabak";

export const categories: { id: Category; label: string; description: string }[] = [
  {
    id: "Frucht",
    label: "Frucht",
    description: "Sonnengereifte Klassiker, direkt aus der Schale.",
  },
  {
    id: "Beeren",
    label: "Beeren",
    description: "Dunkel, saftig, ein bisschen herb im Abgang.",
  },
  {
    id: "Menthol",
    label: "Menthol & Eis",
    description: "Kalt einatmen, kälter ausatmen.",
  },
  {
    id: "Dessert",
    label: "Dessert & Cremig",
    description: "Für alle, die den Nachtisch nie auslassen.",
  },
  {
    id: "Getraenke",
    label: "Getränke & Cocktails",
    description: "Die Bar in einer Wolke.",
  },
  {
    id: "Tabak",
    label: "Tabak & Würzig",
    description: "Erdig, warm, ohne Umwege.",
  },
];

export const categoryColors: Record<Category, string> = {
  Frucht: "#ff5c78",
  Beeren: "#d94ea8",
  Menthol: "#6fe3ff",
  Dessert: "#ffb85c",
  Getraenke: "#a07bff",
  Tabak: "#b8743f",
};

export interface Flavor {
  id: number;
  slug: string;
  name: string;
  category: Category;
  notes: string[];
  tagline: string;
  description: string;
  intensity: "Mild" | "Medium" | "Intensiv";
  disposablePrice: number;
  disposablePuffs: number;
  liquidPrice: number;
  nicotineLevels: number[];
  badge?: "Bestseller" | "Neu" | "Limitiert";
}

export const nicotineLabel = (mg: number) => (mg === 0 ? "0 mg · nikotinfrei" : `${mg} mg`);

export const formatPrice = (price: number) =>
  new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR" }).format(price);

const STANDARD_NIC = [0, 6, 12, 20];

export const flavors: Flavor[] = [
  // Frucht
  {
    id: 1,
    slug: "mango-sunrise",
    name: "Mango Sunrise",
    category: "Frucht",
    notes: ["Reife Mango", "Zitrusschale"],
    tagline: "Mango, wie sie schmeckt, wenn sie fast zu reif ist.",
    description:
      "Vollreife Mango mit einer feinen Zitrusnote im Abgang — süß, ohne künstlich zu kippen.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Bestseller",
  },
  {
    id: 2,
    slug: "wassermelone-splash",
    name: "Wassermelone Splash",
    category: "Frucht",
    notes: ["Wassermelone", "Kühle"],
    tagline: "Der erste Bissen ins Sommerobst, in Dauerschleife.",
    description:
      "Saftige Wassermelone mit einem kühlen Rand, der jeden Zug frisch hält statt schwer zu machen.",
    intensity: "Mild",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 3,
    slug: "pfirsich-nektar",
    name: "Pfirsich Nektar",
    category: "Frucht",
    notes: ["Weißer Pfirsich", "Honig"],
    tagline: "Pfirsich vom Marktstand, nicht aus der Dose.",
    description:
      "Weißer Pfirsich mit einem Hauch Honig — weich, rund, ohne die übliche Süßstoff-Schärfe.",
    intensity: "Mild",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 4,
    slug: "ananas-blitz",
    name: "Ananas Blitz",
    category: "Frucht",
    notes: ["Ananas", "Limette"],
    tagline: "Tropisch, sauer, kein Zurück.",
    description:
      "Grüne Ananas trifft auf einen scharfen Limettenkick — die schärfste Kante im Frucht-Regal.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Neu",
  },
  {
    id: 5,
    slug: "erdbeer-kiss",
    name: "Erdbeer Kiss",
    category: "Frucht",
    notes: ["Walderdbeere", "Sahne-Hauch"],
    tagline: "Die Erdbeere, an die sich jeder erinnert.",
    description:
      "Walderdbeeren mit einem kaum wahrnehmbaren Sahne-Unterton — der Einstiegsgeschmack, den alle kennen.",
    intensity: "Mild",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Bestseller",
  },
  {
    id: 6,
    slug: "kirsch-bombe",
    name: "Kirsch Bombe",
    category: "Frucht",
    notes: ["Schwarzkirsche", "Bittermandel"],
    tagline: "Dunkle Kirsche mit einem Stich Bitterkeit.",
    description:
      "Schwarzkirsche, tief und dicht, mit einer feinen Bittermandel-Note statt reiner Süße.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 7,
    slug: "litschi-rausch",
    name: "Litschi Rausch",
    category: "Frucht",
    notes: ["Litschi", "Rosenwasser"],
    tagline: "Blumig, exotisch, selten auf der Karte.",
    description:
      "Litschi mit einem zarten Rosenwasser-Schimmer — parfümiert, ohne aufdringlich zu werden.",
    intensity: "Medium",
    disposablePrice: 9.4,
    disposablePuffs: 600,
    liquidPrice: 6.4,
    nicotineLevels: STANDARD_NIC,
    badge: "Limitiert",
  },
  {
    id: 8,
    slug: "apfel-crush",
    name: "Apfel Crush",
    category: "Frucht",
    notes: ["Grüner Apfel", "Sternanis"],
    tagline: "Der Apfel, der zurückbeißt.",
    description:
      "Knackig-grüner Apfel mit einer feinen Gewürznote im Hintergrund — sauer zuerst, warm danach.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 9,
    slug: "passionsfrucht-glow",
    name: "Passionsfrucht Glow",
    category: "Frucht",
    notes: ["Maracuja", "Vanilleschote"],
    tagline: "Sauer und süß in einem einzigen Zug.",
    description:
      "Maracuja in voller Säure, abgerundet von einem Tropfen Vanille — kein Gleichgewicht, volle Absicht.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },

  // Beeren
  {
    id: 10,
    slug: "blaubeer-nebel",
    name: "Blaubeer Nebel",
    category: "Beeren",
    notes: ["Waldheidelbeere", "Lavendel"],
    tagline: "Beeren, gepflückt im Halbschatten.",
    description:
      "Waldheidelbeeren mit einer kaum greifbaren Lavendelspur — dunkel, ruhig, nie zu süß.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Bestseller",
  },
  {
    id: 11,
    slug: "himbeer-frost",
    name: "Himbeer Frost",
    category: "Beeren",
    notes: ["Himbeere", "Menthol-Spur"],
    tagline: "Himbeere mit einem kalten Nachhall.",
    description:
      "Süße Himbeere, im Abgang von einer leichten Kühle abgelöst — Beerenfrucht statt Vollmenthol.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 12,
    slug: "brombeer-dusk",
    name: "Brombeer Dusk",
    category: "Beeren",
    notes: ["Brombeere", "Holunderblüte"],
    tagline: "Der letzte Beerenstrauch vor dem Zaun.",
    description:
      "Herbe Brombeere, aufgehellt von Holunderblüte — die erdigste Beere im Sortiment.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 13,
    slug: "johannisbeer-funke",
    name: "Johannisbeer Funke",
    category: "Beeren",
    notes: ["Schwarze Johannisbeere", "Brausezucker"],
    tagline: "Sauer genug, um wach zu bleiben.",
    description:
      "Schwarze Johannisbeere mit einem prickelnden Brausezucker-Finish — kurz, scharf, konzentriert.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Neu",
  },
  {
    id: 14,
    slug: "granatapfel-puls",
    name: "Granatapfel Puls",
    category: "Beeren",
    notes: ["Granatapfel", "Hibiskus"],
    tagline: "Herb, rot, mit spürbarem Biss.",
    description:
      "Granatapfelkerne mit einer teeartigen Hibiskusnote — trocken statt fruchtig-süß.",
    intensity: "Medium",
    disposablePrice: 9.4,
    disposablePuffs: 600,
    liquidPrice: 6.4,
    nicotineLevels: STANDARD_NIC,
    badge: "Limitiert",
  },
  {
    id: 15,
    slug: "heidelbeer-sturm",
    name: "Heidelbeer Sturm",
    category: "Beeren",
    notes: ["Heidelbeere", "Zitronenzeste"],
    tagline: "Heidelbeere, kurz vor dem Umschlag.",
    description:
      "Volle Heidelbeere mit einer scharfen Zitronenzeste im Nachgang — nichts Rundes, nur Spannung.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 16,
    slug: "cranberry-drift",
    name: "Cranberry Drift",
    category: "Beeren",
    notes: ["Cranberry", "Orange"],
    tagline: "Der herbe Rand einer Cocktailkarte.",
    description:
      "Herbe Cranberry, von Orangenschale leicht aufgehellt — trockener Abgang, kein Zucker-Übermut.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 17,
    slug: "beerenmix-aurora",
    name: "Beerenmix Aurora",
    category: "Beeren",
    notes: ["Fünf Beeren", "Minze"],
    tagline: "Fünf Beeren, ein Zug.",
    description:
      "Eine dichte Mischung aus fünf Beerensorten, von einer feinen Minzspur zusammengehalten.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Bestseller",
  },

  // Menthol
  {
    id: 18,
    slug: "arctic-mint",
    name: "Arctic Mint",
    category: "Menthol",
    notes: ["Pfefferminze", "Eiskristall"],
    tagline: "So kalt, wie ein Name es verspricht.",
    description:
      "Reine Pfefferminze in maximaler Kühle — der Referenzpunkt, an dem sich alle anderen Menthols messen.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Bestseller",
  },
  {
    id: 19,
    slug: "polar-ice",
    name: "Polar Ice",
    category: "Menthol",
    notes: ["Menthol", "Neutraler Frost"],
    tagline: "Kein Geschmack außer kalt.",
    description:
      "Fast geschmacksneutrales Menthol — für alle, die ausschließlich die Kühle wollen, sonst nichts.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 20,
    slug: "eukalyptus-kick",
    name: "Eukalyptus Kick",
    category: "Menthol",
    notes: ["Eukalyptus", "Kampfer"],
    tagline: "Fast medizinisch, absichtlich.",
    description:
      "Eukalyptus mit einer leichten Kampfernote — kantiger und erwachsener als klassisches Pfefferminz.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 21,
    slug: "pfefferminz-frost",
    name: "Pfefferminz Frost",
    category: "Menthol",
    notes: ["Pfefferminze", "Karamell-Hauch"],
    tagline: "Kaugummi-Minze, ohne den Zucker.",
    description:
      "Klassische Pfefferminze, von einem winzigen Karamell-Schimmer abgerundet — weicher als Arctic Mint.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 22,
    slug: "gletscher-blau",
    name: "Gletscher Blau",
    category: "Menthol",
    notes: ["Blaue Beeren", "Eis"],
    tagline: "Beere und Kälte, gleich stark.",
    description:
      "Blaue Beerenfrucht auf einem dicken Eisbett — die Menthol-Sorte für alle, die trotzdem Frucht wollen.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Neu",
  },
  {
    id: 23,
    slug: "frostbite-menthol",
    name: "Frostbite Menthol",
    category: "Menthol",
    notes: ["Doppel-Menthol", "Minzöl"],
    tagline: "Für Leute, die 'zu kalt' nicht kennen.",
    description:
      "Doppelt konzentriertes Menthol mit reinem Minzöl — die schärfste Kühlstufe im Regal.",
    intensity: "Intensiv",
    disposablePrice: 9.4,
    disposablePuffs: 600,
    liquidPrice: 6.4,
    nicotineLevels: STANDARD_NIC,
    badge: "Limitiert",
  },
  {
    id: 24,
    slug: "cool-breeze",
    name: "Cool Breeze",
    category: "Menthol",
    notes: ["Wassermelone", "Minze"],
    tagline: "Der ruhigste Punkt im Menthol-Regal.",
    description:
      "Wassermelone mit einer sanften Minzbrise — mild genug für den ganzen Tag.",
    intensity: "Mild",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 25,
    slug: "koala-mint",
    name: "Koala Mint",
    category: "Menthol",
    notes: ["Eukalyptus", "Birne"],
    tagline: "Eukalyptus, aber freundlich.",
    description:
      "Eukalyptus, mit reifer Birne abgemildert — die zugänglichste Variante der scharfen Kräuternote.",
    intensity: "Mild",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },

  // Dessert
  {
    id: 26,
    slug: "vanille-wolke",
    name: "Vanille Wolke",
    category: "Dessert",
    notes: ["Bourbon-Vanille", "Sahne"],
    tagline: "Nichts als Vanille, dafür richtig.",
    description:
      "Echte Bourbon-Vanille mit leichter Sahne — schlicht, aber ohne die künstliche Süße billiger Kopien.",
    intensity: "Mild",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Bestseller",
  },
  {
    id: 27,
    slug: "karamell-schmelz",
    name: "Karamell Schmelz",
    category: "Dessert",
    notes: ["Gesalzenes Karamell", "Butter"],
    tagline: "Karamell, das kurz vorm Anbrennen war.",
    description:
      "Gesalzenes Karamell mit gebräunter Butter — tief und leicht rauchig statt nur süß.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 28,
    slug: "custard-dream",
    name: "Custard Dream",
    category: "Dessert",
    notes: ["Eiercreme", "Muskat"],
    tagline: "Der Pudding, der nie ganz fest wird.",
    description:
      "Cremige Eiercreme mit einer Prise Muskat — dickflüssig, warm, fast schon ein Dessert für sich.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 29,
    slug: "kokos-latte",
    name: "Kokos Latte",
    category: "Dessert",
    notes: ["Kokosmilch", "Espresso"],
    tagline: "Kaffeepause, tropisch verschoben.",
    description:
      "Kokosmilch mit einem Schuss Espresso — der Latte für alle, die den Strand dem Büro vorziehen.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Neu",
  },
  {
    id: 30,
    slug: "tiramisu-nebel",
    name: "Tiramisu Nebel",
    category: "Dessert",
    notes: ["Mascarpone", "Kakao"],
    tagline: "Löffelweise, ohne den Löffel.",
    description:
      "Mascarpone und Kakaopulver, so dicht geschichtet wie das Original im Glas.",
    intensity: "Medium",
    disposablePrice: 9.4,
    disposablePuffs: 600,
    liquidPrice: 6.4,
    nicotineLevels: STANDARD_NIC,
    badge: "Limitiert",
  },
  {
    id: 31,
    slug: "zimtrolle",
    name: "Zimtrolle",
    category: "Dessert",
    notes: ["Zimt", "Frischer Teig"],
    tagline: "Der Duft aus der Bäckerei, eingefangen.",
    description:
      "Warmer Zimt auf frisch gebackenem Teig — die Sorte, die man riecht, bevor man sie schmeckt.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 32,
    slug: "donut-glaze",
    name: "Donut Glaze",
    category: "Dessert",
    notes: ["Zuckerglasur", "Himbeerfüllung"],
    tagline: "Die Glasur, nicht der Rest.",
    description:
      "Süße Zuckerglasur mit einem Herz aus Himbeerfüllung — konzentriert auf den besten Bissen.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 33,
    slug: "marshmallow-fluff",
    name: "Marshmallow Fluff",
    category: "Dessert",
    notes: ["Marshmallow", "Vanilleflocke"],
    tagline: "Weich, süß, fast ohne Kante.",
    description:
      "Geröstetes Marshmallow mit einer feinen Vanilleflocke — die weichste Landung im Dessert-Regal.",
    intensity: "Mild",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },

  // Getraenke
  {
    id: 34,
    slug: "cola-rausch",
    name: "Cola Rausch",
    category: "Getraenke",
    notes: ["Cola", "Vanille-Karamell"],
    tagline: "Die Dose, die man nie ganz leert.",
    description:
      "Klassische Cola mit Vanille-Karamell-Unterton — nah am Original, ohne die Kohlensäure zu brauchen.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Bestseller",
  },
  {
    id: 35,
    slug: "energy-rocket",
    name: "Energy Rocket",
    category: "Getraenke",
    notes: ["Guarana", "Traube"],
    tagline: "Der Energy-Drink, ohne den Absturz.",
    description:
      "Guarana-Schärfe mit einer süßen Traubennote — laut, schnell, kein bisschen subtil.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 36,
    slug: "mojito-fresh",
    name: "Mojito Fresh",
    category: "Getraenke",
    notes: ["Limette", "Minze"],
    tagline: "Die Bar-Theke, ohne den Rum.",
    description:
      "Frische Limette mit zerstoßener Minze — der alkoholfreie Mojito für unterwegs.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 37,
    slug: "pina-colada-wave",
    name: "Piña Colada Wave",
    category: "Getraenke",
    notes: ["Ananas", "Kokosnuss"],
    tagline: "Strandliege, in einem Zug.",
    description:
      "Ananas und Kokosnuss, cremig geschüttelt — der Urlaub, den der Kalender gerade nicht hergibt.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Neu",
  },
  {
    id: 38,
    slug: "lemonade-twist",
    name: "Lemonade Twist",
    category: "Getraenke",
    notes: ["Zitrone", "Erdbeere"],
    tagline: "Der Kiosk-Becher aus Kindertagen.",
    description:
      "Klassische Zitronenlimonade mit einem Erdbeer-Twist — süß-sauer, wie am Straßenrand verkauft.",
    intensity: "Mild",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 39,
    slug: "root-beer-float",
    name: "Root Beer Float",
    category: "Getraenke",
    notes: ["Sarsaparille", "Vanilleeis"],
    tagline: "Amerikanisch, kompromisslos süß.",
    description:
      "Würzige Sarsaparille mit einer Kugel Vanilleeis obendrauf — ein Geschmack, den man liebt oder nie versteht.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 40,
    slug: "pfirsich-eistee",
    name: "Pfirsich Eistee",
    category: "Getraenke",
    notes: ["Schwarztee", "Pfirsich"],
    tagline: "Die Kanne vom Nachmittag im Garten.",
    description:
      "Kalt gebrühter Schwarztee mit reifem Pfirsich — zurückhaltend süß, mit echter Tee-Bitterkeit.",
    intensity: "Mild",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 41,
    slug: "ginger-spark",
    name: "Ginger Spark",
    category: "Getraenke",
    notes: ["Ingwer", "Limette"],
    tagline: "Schärfer, als der Name klingen lässt.",
    description:
      "Scharfer Ingwer mit einem Spritzer Limette — die trockenste, erwachsenste Sorte im Getränke-Regal.",
    intensity: "Intensiv",
    disposablePrice: 9.4,
    disposablePuffs: 600,
    liquidPrice: 6.4,
    nicotineLevels: STANDARD_NIC,
    badge: "Limitiert",
  },
  {
    id: 42,
    slug: "blue-slush",
    name: "Blue Slush",
    category: "Getraenke",
    notes: ["Blaue Himbeere", "Slush-Eis"],
    tagline: "Der Kino-Becher, jetzt ohne Brainfreeze.",
    description:
      "Blaue Himbeere im Slush-Eis-Stil — grell süß, eiskalt serviert, pure Nostalgie.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },

  // Tabak
  {
    id: 43,
    slug: "tabak-classic",
    name: "Tabak Classic",
    category: "Tabak",
    notes: ["Virginia-Tabak", "Holz"],
    tagline: "Der Ausgangspunkt, unverändert.",
    description:
      "Reiner Virginia-Tabak-Geschmack mit trockener Holznote — die Referenz, an der sich der Rest misst.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Bestseller",
  },
  {
    id: 44,
    slug: "bourbon-tabak",
    name: "Bourbon Tabak",
    category: "Tabak",
    notes: ["Tabak", "Bourbon-Fass"],
    tagline: "Tabak, der in Eiche gelegen hat.",
    description:
      "Kräftiger Tabak mit einer Bourbon-Fassnote — schwer, warm, mit langem Abgang.",
    intensity: "Intensiv",
    disposablePrice: 9.4,
    disposablePuffs: 600,
    liquidPrice: 6.4,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 45,
    slug: "zimt-tabak",
    name: "Zimt Tabak",
    category: "Tabak",
    notes: ["Tabak", "Zimt"],
    tagline: "Zwei Klassiker, ein Zug.",
    description:
      "Trockener Tabak, von warmem Zimt durchzogen — die würzigste Brücke zwischen Tabak und Dessert.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 46,
    slug: "chai-spice",
    name: "Chai Spice",
    category: "Tabak",
    notes: ["Schwarzer Tee", "Kardamom"],
    tagline: "Der Gewürzstand, nicht der Zigarrenladen.",
    description:
      "Schwarzer Tee mit Kardamom, Nelke und Zimt — würzig und warm, ganz ohne echten Tabak.",
    intensity: "Medium",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
    badge: "Neu",
  },
  {
    id: 47,
    slug: "vanille-tabak",
    name: "Vanille Tabak",
    category: "Tabak",
    notes: ["Tabak", "Vanille"],
    tagline: "Die weichste Tür in den Tabak hinein.",
    description:
      "Milder Tabak, von Vanille abgerundet — der Einstieg für alle, die reinen Tabak zu hart finden.",
    intensity: "Mild",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 48,
    slug: "anis-herb",
    name: "Anis Herb",
    category: "Tabak",
    notes: ["Anis", "Lakritz"],
    tagline: "Für Lakritz-Menschen, sonst niemanden.",
    description:
      "Kräftiger Anis mit dunkler Lakritznote — kompromisslos, kein Geschmack für den Übergang.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 49,
    slug: "kaffee-roest",
    name: "Kaffee Röst",
    category: "Tabak",
    notes: ["Espresso", "Dunkle Röstung"],
    tagline: "Die letzte Tasse vor Feierabend.",
    description:
      "Dunkel gerösteter Espresso, bitter und dicht — für alle, die Süße lieber woanders suchen.",
    intensity: "Intensiv",
    disposablePrice: 8.9,
    disposablePuffs: 600,
    liquidPrice: 5.9,
    nicotineLevels: STANDARD_NIC,
  },
  {
    id: 50,
    slug: "clove-ember",
    name: "Clove Ember",
    category: "Tabak",
    notes: ["Gewürznelke", "Glut"],
    tagline: "Die Glut, kurz bevor sie erlischt.",
    description:
      "Gewürznelke mit einem rauchigen Unterton — die dunkelste, erwachsenste Sorte im ganzen Sortiment.",
    intensity: "Intensiv",
    disposablePrice: 9.4,
    disposablePuffs: 600,
    liquidPrice: 6.4,
    nicotineLevels: STANDARD_NIC,
    badge: "Limitiert",
  },
];

export const getFlavor = (slug: string) => flavors.find((f) => f.slug === slug);

export const getRelatedFlavors = (flavor: Flavor, limit = 3) =>
  flavors.filter((f) => f.category === flavor.category && f.slug !== flavor.slug).slice(0, limit);

// One standout per category, kept small on purpose — used by the 3D
// flavor ring, which is a compact showcase rather than the full catalog.
export const ringFlavors = flavors.filter((f) => f.badge === "Bestseller");
